from __future__ import annotations
import argparse
import hashlib
import json
import sys
from pathlib import Path
from sqlalchemy import delete, select
ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from backend.app.db import Base, SessionLocal, engine  # noqa: E402
from backend.app.models import Document, Formation, Incident, Scenario, Well  # noqa: E402
DATA = ROOT / "data" / "synthetic"
def load(name: str):
    return json.loads((DATA / name).read_text(encoding="utf-8"))
def seed(reset: bool = False, confirm_reset_demo: bool = False) -> None:
    if reset and not confirm_reset_demo:
        raise SystemExit("Refusing reset: pass --confirm-reset-demo to delete synthetic demo rows")
    Base.metadata.create_all(engine)
    wells = load("wells.json")
    with SessionLocal() as db:
        if reset:
            demo_well_ids = [row["id"] for row in wells]
            db.execute(delete(Incident).where(Incident.is_synthetic.is_(True)))
            db.execute(delete(Formation).where(Formation.well_id.in_(demo_well_ids)))
            db.execute(delete(Scenario).where(Scenario.id.like("scenario-%")))
            db.execute(delete(Document).where(Document.is_synthetic.is_(True)))
            db.execute(delete(Well).where(Well.id.in_(demo_well_ids)))
            db.commit()
        for row in wells:
            if db.get(Well, row["id"]):
                continue
            db.add(Well(**row, data_origin="synthetic", demo_label="Fictional Kanchan Ridge demo"))
            for index, formation_name in enumerate([item["name"] for item in load("formations.json")]):
                db.add(Formation(well_id=row["id"], name=formation_name, top_depth_m=float(index * 500), base_depth_m=float((index + 1) * 500)))
        for row in load("scenarios.json"):
            if not db.get(Scenario, row["id"]):
                db.add(Scenario(**{key: value for key, value in row.items() if key != "is_synthetic"}))
        for report in load("reports.json"):
            path = DATA / report["filename"]
            content = path.read_bytes()
            document = db.scalar(select(Document).where(Document.document_id == report["document_id"]))
            if not document:
                db.add(Document(document_id=report["document_id"], filename=report["filename"], document_type="report", storage_path=str(path), content_sha256=hashlib.sha256(content).hexdigest(), file_size_bytes=len(content), mime_type="text/plain", extracted_text=content.decode("utf-8"), extraction_status="extracted", extraction_confidence=1.0, review_status="verified", provenance="generated by scripts/generate_demo_data.py", page_count=1, data_origin="synthetic", is_synthetic=True))
        db.flush()
        document_ids = {doc.document_id: doc.id for doc in db.scalars(select(Document)).all()}
        for row in load("events.json"):
            if db.get(Incident, row["id"]):
                continue
            event = dict(row)
            event["formation_name"] = event.pop("formation")
            event["source_document_id"] = document_ids.get(event["source_document_id"])
            event["data_origin"] = "synthetic"
            event["extraction_status"] = "verified"
            db.add(Incident(**event))
        db.commit()
        print(f"Demo seed complete: {len(wells)} wells, 8 formations, 60 events, 3 scenarios; non-demo data preserved.")
if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--reset", action="store_true", help="Delete synthetic demo rows before reseeding")
    parser.add_argument("--confirm-reset-demo", action="store_true", help="Required with --reset")
    args = parser.parse_args()
    seed(args.reset, args.confirm_reset_demo)
